// Code generated by go generate ./saveparser/thebibites; DO NOT EDIT.

package thebibites

var bibiteColumnPaths = map[string]string{
	"species_id":           "genes.speciesID",
	"generation":           "genes.gen",
	"dead":                 "body.dead",
	"dying":                "body.dying",
	"health":               "body.health",
	"energy":               "body.energy",
	"time_alive":           "clock.timeAlive",
	"transform_position_x": "transform.position[0]",
	"transform_position_y": "transform.position[1]",
	"transform_rotation":   "transform.rotation",
	"transform_scale":      "transform.scale",
	"rb2d_px":              "rb2d.px",
	"rb2d_py":              "rb2d.py",
	"rb2d_vx":              "rb2d.vx",
	"rb2d_vy":              "rb2d.vy",
	"rb2d_r":               "rb2d.r",
}

var bibiteBodyColumnPaths = map[string]string{
	"d2_size":               "body.d2Size",
	"fat_reserves_amount":   "body.fatReservesAmount",
	"attacked_dmg":          "body.attackedDmg",
	"times_attacked":        "body.timesAttacked",
	"total_damage_suffered": "body.totalDamageSuffered",
	"brain_ticks_count":     "body.brainTicksCount",
	"vision_lookup_count":   "body.visionLookupCount",
	"vision_sensing_count":  "body.visionSensingCount",
	"corpse_energy_offset":  "body.corpseEnergyOffset",
}

var bibiteMouthColumnPaths = map[string]string{
	"attacked_last_frame": "body.mouth.attackedLastFrame",
	"bibites_bitten":      "body.mouth.bibitesBitten",
	"bite_progress":       "body.mouth.biteProgress",
	"murdered_area":       "body.mouth.murderedArea",
	"total_damage_dealt":  "body.mouth.totalDamageDealt",
	"total_murders":       "body.mouth.totalMurders",
}

var bibitePheromoneColumnPaths = map[string]string{
	"progress": "body.phero.progress",
}

var bibiteEggLayerColumnPaths = map[string]string{
	"egg_progress": "body.eggLayer.eggProgress",
	"n_eggs_laid":  "body.eggLayer.nEggsLaid",
}

var bibiteControlColumnPaths = map[string]string{
	"total_travel": "body.control.totalTravel",
}

var eggColumnPaths = map[string]string{
	"species_id":           "genes.speciesID",
	"generation":           "genes.gen",
	"hatch_progress":       "egg.hatchProgress",
	"energy":               "egg.energy",
	"transform_position_x": "transform.position[0]",
	"transform_position_y": "transform.position[1]",
	"transform_rotation":   "transform.rotation",
	"transform_scale":      "transform.scale",
	"rb2d_px":              "rb2d.px",
	"rb2d_py":              "rb2d.py",
	"rb2d_vx":              "rb2d.vx",
	"rb2d_vy":              "rb2d.vy",
	"rb2d_r":               "rb2d.r",
}

var brainNodeColumnKeys = map[string]string{
	"node_index":      "Index",
	"innovation":      "Inov",
	"node_type":       "Type",
	"type_name":       "TypeName",
	"node_desc":       "Desc",
	"archetype":       "archetype",
	"base_activation": "baseActivation",
	"value":           "Value",
	"last_input":      "LastInput",
	"last_output":     "LastOutput",
}

var brainSynapseColumnKeys = map[string]string{
	"innovation": "Inov",
	"node_in":    "NodeIn",
	"node_out":   "NodeOut",
	"weight":     "Weight",
	"enabled":    "En",
}

var bibiteStomachContentColumnFields = map[string]string{
	"material":             "material",
	"amount":               "amount",
	"average_chunk_amount": "averageChunkAmount",
}

var pelletColumnPaths = map[string]string{
	"material":                "pellet.material",
	"amount":                  "pellet.amount",
	"matter_decay_time_alive": "matterDecay.timeAlive",
	"matter_decay_rot_amount": "matterDecay.rotAmount",
	"transform_position_x":    "transform.position[0]",
	"transform_position_y":    "transform.position[1]",
	"transform_rotation":      "transform.rotation",
	"transform_scale":         "transform.scale",
	"rb2d_px":                 "rb2d.px",
	"rb2d_py":                 "rb2d.py",
	"rb2d_vx":                 "rb2d.vx",
	"rb2d_vy":                 "rb2d.vy",
	"rb2d_r":                  "rb2d.r",
}

var pheromoneColumnPaths = map[string]string{
	"transform_position_x": "transform.position[0]",
	"transform_position_y": "transform.position[1]",
	"transform_rotation":   "transform.rotation",
	"transform_scale":      "transform.scale",
	"r_strength":           "phero.Rstrength",
	"g_strength":           "phero.Gstrength",
	"b_strength":           "phero.Bstrength",
	"nr":                   "phero.nR",
	"ng":                   "phero.nG",
	"nb":                   "phero.nB",
}

var settingsZoneColumnPaths = map[string]string{
	"name":         "name",
	"material":     "material",
	"distribution": "distribution",
}
